version: "3.9"

services:

  web:
    build: .
    container_name: flask_app

    ports:
      - "5000:5000"

    depends_on:
      - db

    environment:
      DB_HOST: db
      DB_NAME: mydatabase
      DB_USER: postgres
      DB_PASSWORD: postgres

  db:
    image: postgres:16

    container_name: postgres_db

    restart: always

    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

#for 6 